export {
  SUBCELL,
  FACING_COUNT,
  FACING_VECTORS,
  cellCenter,
  toCell,
  isqrt,
  distSq,
  facingFromDelta,
} from './fixed.js';
export { nextU32, nextInt, type RngCarrier } from './rng.js';
export {
  TERRAIN_DIRT,
  TERRAIN_WATER,
  TERRAIN_ROCK,
  TERRAIN_TREE,
  TERRAIN_GRASS,
  RESOURCE_NONE,
  RESOURCE_ORE,
  RESOURCE_GEMS,
  MAP_TYPES,
  MAP_NAMES,
  cellIndex,
  inBounds,
  isPassableTerrain,
  isPassableKind,
  cellsAroundRect,
  stampResourcePatch,
  generateTerrain,
  type GridView,
  type MapType,
} from './map.js';
export {
  UNIT_RULES,
  BUILDING_RULES,
  FACTIONS,
  FACTION_NAMES,
  WALL_LEVELS,
  unitRule,
  buildingRule,
  isBuildingType,
  isUnitType,
  availableToFaction,
  sellRefund,
  BUILD_ADJACENCY,
  buildAdjacency,
  HARVEST_CAPACITY,
  HARVEST_RATE,
  GEM_VALUE,
  REGROWTH_INTERVAL,
  REGROWTH_AMOUNT,
  REGROWTH_CAP,
  REPAIR_HP_PER_TICK,
  REPAIR_COST_PER_TICK,
  REPAIR_RADIUS,
  VEHICLE_REPAIR_HP_PER_TICK,
  VEHICLE_REPAIR_COST_PER_TICK,
  VEHICLE_REPAIR_REACH,
  SUPERWEAPON_STATS,
  SUPERWEAPON_CHARGE_TICKS,
  SUPERWEAPON_TRAVEL_TICKS,
  type UnitRule,
  type UnitType,
  type BuildingRule,
  type BuildingType,
  type WeaponRule,
  type WeaponFx,
  type ArmorClass,
  type UnitCategory,
  type ProductionCategory,
  type Faction,
  type SuperweaponKind,
  type SuperweaponStats,
  type AiDifficulty,
} from './rules.js';
export type { SimEvent } from './events.js';
export {
  createGame,
  spawnUnit,
  constructBuilding,
  dockCell,
  serialize,
  deserialize,
  PLAYER_SPAWNS,
  FOG_HIDDEN,
  FOG_EXPLORED,
  FOG_VISIBLE,
  type GameState,
  type GameOptions,
  type Unit,
  type UnitOrder,
  type Building,
  type Projectile,
  type Strike,
  type Player,
  type ProductionQueue,
  type PathCell,
} from './state.js';
export {
  findTarget,
  targetOwner,
  aimPoint,
  targetDistSq,
  damageTarget,
  nearestEnemyUnit,
  nearestEnemyBuilding,
  buildingMaxHp,
  type Target,
} from './targeting.js';
export { fnv1a, hashState } from './hash.js';
export { findPath, type PathOptions } from './path/astar.js';
export { applyCommands, type Command } from './commands.js';
export { canPlaceBuilding } from './systems/placement.js';
export { powerBalance } from './systems/production.js';
export { aiSystem } from './ai/controller.js';
export { tick, TICKS_PER_SECOND, TICK_MS } from './tick.js';
export {
  INPUT_DELAY_TICKS,
  HASH_INTERVAL_TICKS,
  DEFAULT_SERVER_PORT,
  type ClientMessage,
  type ServerMessage,
} from './protocol.js';
